### ISSUE TITLE
Errors when trying to run the code locally via `sam invoke`

### ISSUE THREAD

**Issue by burinc** [FieryCod/holy-lambda#26]
Hi @FieryCod,

Thanks for the great library.

I am getting the following errors when trying to run the code locally via SAM.

My env:

```
java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

The command executed:

```
make dry-api # works great I can see the server is start locally

# then I try to invoke sam locally using this command
echo '{"message": "Hey, are you there?" }' | sam local invoke "HelloLambdaFunction" --event -
```

I am getting the following errors:

```
Reading invoke payload from stdin (you can also pass it from file with --event)
Invoking hello-lambda.core.HelloLambda (java11)
Decompressing /Users/bchoomnuan/b12n/FieryCod--holy-lambda/examples/hello-lambda/target/output.jar
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-java11:rapid-1.15.0.

Mounting /private/var/folders/c7/gkpgtgtj2fd40xv6v4ll6tpdhxy_sz/T/tmp3wf1wzgt as /var/task:ro,delegated inside runtime container
START RequestId: 12bc765d-b2f9-413d-823a-d018f3aecd63 Version: $LATEST
Error loading class hello-lambda.core.HelloLambda: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Unknown Source)
    at clojure.lang.RT.classForName(RT.java:2212)
    at clojure.lang.RT.classForName(RT.java:2221)
    at clojure.lang.RT.loadClassForName(RT.java:2240)
    at clojure.lang.RT.load(RT.java:449)
    at clojure.lang.RT.load(RT.java:424)
    at clojure.core$load$fn__6857.invoke(core.clj:6115)
    at clojure.core$load.invokeStatic(core.clj:6114)
    at clojure.core$load.doInvoke(core.clj:6098)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5897)
    at clojure.core$load_one.invoke(core.clj:5892)
    at clojure.core$load_lib$fn__6797.invoke(core.clj:5937)
    at clojure.core$load_lib.invokeStatic(core.clj:5936)
    at clojure.core$load_lib.doInvoke(core.clj:5917)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$load_libs.invokeStatic(core.clj:5974)
    at clojure.core$load_libs.doInvoke(core.clj:5958)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$require.invokeStatic(core.clj:5996)
    at clojure.main$loading__6738__auto____9000.invoke(main.clj:11)
    at clojure.main__init.load(Unknown Source)
    at clojure.main__init.<clinit>(Unknown Source)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Unknown Source)
    at clojure.lang.RT.classForName(RT.java:2212)
    at clojure.lang.RT.classForName(RT.java:2221)
    at clojure.lang.RT.loadClassForName(RT.java:2240)
    at clojure.lang.RT.load(RT.java:449)
    at clojure.lang.RT.load(RT.java:424)
    at clojure.core$load$fn__6857.invoke(core.clj:6115)
    at clojure.core$load.invokeStatic(core.clj:6114)
    at clojure.core$load.doInvoke(core.clj:6098)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5897)
    at clojure.core$load_one.invoke(core.clj:5892)
    at clojure.core$load_lib$fn__6797.invoke(core.clj:5937)
    at clojure.core$load_lib.invokeStatic(core.clj:5936)
    at clojure.core$load_lib.doInvoke(core.clj:5917)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$load_libs.invokeStatic(core.clj:5974)
    at clojure.core$load_libs.doInvoke(core.clj:5958)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$require.invokeStatic(core.clj:5996)
    at clojure.core.server$loading__6738__auto____8867.invoke(server.clj:9)
    at clojure.core.server__init.load(Unknown Source)
    at clojure.core.server__init.<clinit>(Unknown Source)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Unknown Source)
    at clojure.lang.RT.classForName(RT.java:2212)
    at clojure.lang.RT.classForName(RT.java:2221)
    at clojure.lang.RT.loadClassForName(RT.java:2240)
    at clojure.lang.RT.load(RT.java:449)
    at clojure.lang.RT.load(RT.java:424)
    at clojure.core$load$fn__6857.invoke(core.clj:6115)
    at clojure.core$load.invokeStatic(core.clj:6114)
    at clojure.core$load.doInvoke(core.clj:6098)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5897)
    at clojure.core$load_one.invoke(core.clj:5892)
    at clojure.core$load_lib$fn__6797.invoke(core.clj:5937)
    at clojure.core$load_lib.invokeStatic(core.clj:5936)
    at clojure.core$load_lib.doInvoke(core.clj:5917)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$load_libs.invokeStatic(core.clj:5974)
    at clojure.core$load_libs.doInvoke(core.clj:5958)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$require.invokeStatic(core.clj:5996)
    at clojure.core$require.doInvoke(core.clj:5996)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at clojure.lang.RT.doInit(RT.java:491)
    at clojure.lang.RT.init(RT.java:467)
    at clojure.lang.Util.loadWithClass(Util.java:248)
    at hello-lambda.core.HelloLambda.<clinit>(Unknown Source)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Unknown Source)
Caused by: Syntax error macroexpanding clojure.core/ns at (clojure/walk.clj:21:1).
Syntax error compiling at (clojure/core/specs/alpha.clj:1:1).
    at clojure.lang.Compiler.checkSpecs(Compiler.java:6976)
    at clojure.lang.Compiler.macroexpand1(Compiler.java:6992)
    at clojure.lang.Compiler.macroexpand(Compiler.java:7079)
    at clojure.lang.Compiler.eval(Compiler.java:7165)
    at clojure.lang.Compiler.load(Compiler.java:7640)
    at clojure.lang.RT.loadResourceScript(RT.java:381)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.load(RT.java:459)
    at clojure.lang.RT.load(RT.java:424)
    at clojure.core$load$fn__6857.invoke(core.clj:6115)
    at clojure.core$load.invokeStatic(core.clj:6114)
    at clojure.core$load.doInvoke(core.clj:6098)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5897)
    at clojure.core$load_one.invoke(core.clj:5892)
    at clojure.core$load_lib$fn__6797.invoke(core.clj:5937)
    at clojure.core$load_lib.invokeStatic(core.clj:5936)
    at clojure.core$load_lib.doInvoke(core.clj:5917)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$load_libs.invokeStatic(core.clj:5974)
    at clojure.core$load_libs.doInvoke(core.clj:5958)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$require.invokeStatic(core.clj:5996)
    at clojure.core$require.doInvoke(core.clj:5996)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at clojure.spec.alpha$loading__6434__auto____1663.invoke(alpha.clj:9)
    at clojure.spec.alpha__init.load(Unknown Source)
    at clojure.spec.alpha__init.<clinit>(Unknown Source)
    ... 84 more
Caused by: Syntax error compiling at (clojure/core/specs/alpha.clj:1:1).
    at clojure.core$throw_if.invokeStatic(core.clj:5856)
    at clojure.core$check_cyclic_dependency.invokeStatic(core.clj:5988)
    at clojure.core$load.invokeStatic(core.clj:6109)
    at clojure.core$load.doInvoke(core.clj:6098)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invokeStatic(core.clj:5897)
    at clojure.core$load_one.invoke(core.clj:5892)
    at clojure.core$load_lib$fn__6797.invoke(core.clj:5937)
    at clojure.core$load_lib.invokeStatic(core.clj:5936)
    at clojure.core$load_lib.doInvoke(core.clj:5917)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$load_libs.invokeStatic(core.clj:5974)
    at clojure.core$load_libs.doInvoke(core.clj:5958)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invokeStatic(core.clj:669)
    at clojure.core$require.invokeStatic(core.clj:5996)
    at clojure.core$require.doInvoke(core.clj:5996)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core.specs.alpha$eval1309$loading__6738__auto____1310.invoke(alpha.clj:1)
    at clojure.core.specs.alpha$eval1309.invokeStatic(alpha.clj:1)
    at clojure.core.specs.alpha$eval1309.invoke(alpha.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:7181)
    at clojure.lang.Compiler.eval(Compiler.java:7170)
    at clojure.lang.Compiler.load(Compiler.java:7640)
    at clojure.lang.RT.loadResourceScript(RT.java:381)
    at clojure.lang.RT.loadResourceScript(RT.java:372)
    at clojure.lang.RT.load(RT.java:459)
    at clojure.lang.RT.load(RT.java:424)
    at clojure.lang.Compiler.ensureMacroCheck(Compiler.java:6962)
    at clojure.lang.Compiler.checkSpecs(Compiler.java:6974)
    ... 113 more
Caused by: java.lang.Exception: Cyclic load dependency: [ /clojure/spec/alpha ]->/clojure/walk->[ /clojure/spec/alpha ]->/clojure/main->/clojure/core/server
    ... 139 more

time="2021-01-03T21:27:08.903" level=panic msg="ReplyStream not available"
2021/01/03 21:27:08 http: panic serving 127.0.0.1:53576: &{0xc000158000 map[] 2021-01-03 21:27:08.9036281 +0000 UTC m=+7.279948101 panic <nil> ReplyStream not available <nil> <nil> }
goroutine 14 [running]:
net/http.(*conn).serve.func1(0xc0000755e0)
    /usr/local/go/src/net/http/server.go:1800 +0x139
```
Any help would be greatly appreciated.
Thanks

**Comment by FieryCod** [comment]
@burinc Investigating why `java11` runtime triggers the error. In the meantime try switching to `java8`.

**Comment by FieryCod** [comment]
@burinc @ekoontz There are two possible workarounds for now. Either switch to java8 or use Clojure 1.10.0 :)

**Comment by burinc** [comment]
Will try with newer version of Clojure.
Thanks
